var F5=["BN","BN","BN","BN","BN","BN","BN","BN","BN","S","B","S","WS","B","BN","BN","BN","BN","BN","BN","BN","BN","BN","BN","BN","BN","BN","BN","B","B","B","S","WS","ON","ON","ET","ET","ET","ON","ON","ON","ON","ON","ON","CS","ON","CS","ON","EN","EN","EN","EN","EN","EN","EN","EN","EN","EN","ON","ON","ON","ON","ON","ON","ON","L","L","L","L","L","L","L","L","L","L","L","L","L","L","L","L","L","L","L","L","L","L","L","L","L","L","ON","ON","ON","ON","ON","ON","L","L","L","L","L","L","L","L","L","L","L","L","L","L","L","L","L","L","L","L","L","L","L","L","L","L","ON","ON","ON","ON","BN","BN","BN","BN","BN","BN","B","BN","BN","BN","BN","BN","BN","BN","BN","BN","BN","BN","BN","BN","BN","BN","BN","BN","BN","BN","BN","BN","BN","BN","BN","BN","BN","CS","ON","ET","ET","ET","ET","ON","ON","ON","ON","L","ON","ON","ON","ON","ON","ET","ET","EN","EN","ON","L","ON","ON","ON","EN","L","ON","ON","ON","ON","ON","L","L","L","L","L","L","L","L","L","L","L","L","L","L","L","L","L","L","L","L","L","L","L","ON","L","L","L","L","L","L","L","L","L","L","L","L","L","L","L","L","L","L","L","L","L","L","L","L","L","L","L","L","L","L","L","ON","L","L","L","L","L","L","L","L"],_5=["AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","CS","AL","ON","ON","NSM","NSM","NSM","NSM","NSM","NSM","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","NSM","NSM","NSM","NSM","NSM","NSM","NSM","NSM","NSM","NSM","NSM","NSM","NSM","NSM","AL","AL","AL","AL","AL","AL","AL","AN","AN","AN","AN","AN","AN","AN","AN","AN","AN","ET","AN","AN","AL","AL","AL","NSM","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","NSM","NSM","NSM","NSM","NSM","NSM","NSM","NSM","NSM","NSM","NSM","NSM","NSM","NSM","NSM","NSM","NSM","NSM","NSM","ON","NSM","NSM","NSM","NSM","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL","AL"];
function j5(J){if(J<=255)return F5[J];if(1424<=J&&J<=1524)return"R";if(1536<=J&&J<=1791)return _5[J&255];if(1792<=J&&J<=2220)return"AL";return"L"}
function R5(J){let Q=J.length;if(Q===0)return null;let $=Array(Q),X=0;for(let V=0;V<Q;V++){let U=j5(J.charCodeAt(V));if(U==="R"||U==="AL"||U==="AN")X++;$[V]=U}if(X===0)return null;let q=Q/X<0.3?0:1,Z=new Int8Array(Q);for(let V=0;V<Q;V++)Z[V]=q;let Y=q&1?"R":"L",D=Y,N=D;for(let V=0;V<Q;V++)if($[V]==="NSM")$[V]=N;else N=$[V];N=D;for(let V=0;V<Q;V++){let U=$[V];if(U==="EN")$[V]=N==="AL"?"AN":"EN";else if(U==="R"||U==="L"||U==="AL")N=U}for(let V=0;V<Q;V++)if($[V]==="AL")$[V]="R";for(let V=1;V<Q-1;V++){if($[V]==="ES"&&$[V-1]==="EN"&&$[V+1]==="EN")$[V]="EN";if($[V]==="CS"&&($[V-1]==="EN"||$[V-1]==="AN")&&$[V+1]===$[V-1])$[V]=$[V-1]}for(let V=0;V<Q;V++){if($[V]!=="EN")continue;let U;for(U=V-1;U>=0&&$[U]==="ET";U--)$[U]="EN";for(U=V+1;U<Q&&$[U]==="ET";U++)$[U]="EN"}for(let V=0;V<Q;V++){let U=$[V];if(U==="WS"||U==="ES"||U==="ET"||U==="CS")$[V]="ON"}N=D;for(let V=0;V<Q;V++){let U=$[V];if(U==="EN")$[V]=N==="L"?"L":"EN";else if(U==="R"||U==="L")N=U}for(let V=0;V<Q;V++){if($[V]!=="ON")continue;let U=V+1;while(U<Q&&$[U]==="ON")U++;let j=V>0?$[V-1]:D,f=U<Q?$[U]:D,O=j!=="L"?"R":"L";if(O===(f!=="L"?"R":"L"))for(let G=V;G<U;G++)$[G]=O;V=U-1}for(let V=0;V<Q;V++)if($[V]==="ON")$[V]=Y;for(let V=0;V<Q;V++){let U=$[V];if((Z[V]&1)===0){if(U==="R")Z[V]++;else if(U==="AN"||U==="EN")Z[V]+=2}else if(U==="L"||U==="AN"||U==="EN")Z[V]++}return Z}
function B0(J,Q){let $=R5(J);if($===null)return null;let X=new Int8Array(Q.length);for(let q=0;q<Q.length;q++)X[q]=$[Q[q]];return X}
var H5=/[ \t\n\r\f]+/g,b5=/[\t\n\r\f]| {2,}|^ | $/;
function v5(J){let Q=J??"normal";return Q==="pre-wrap"?{mode:Q,preserveOrdinarySpaces:!0,preserveHardBreaks:!0}:{mode:Q,preserveOrdinarySpaces:!1,preserveHardBreaks:!1}}
function P5(J){if(!b5.test(J))return J;let Q=J.replace(H5," ");if(Q.charCodeAt(0)===32)Q=Q.slice(1);if(Q.length>0&&Q.charCodeAt(Q.length-1)===32)Q=Q.slice(0,-1);return Q}
function G5(J){if(!/[\r\f]/.test(J))return J.replace(/\r\n/g,`\n`);return J.replace(/\r\n/g,`\n`).replace(/[\r\f]/g,`\n`)}
var D0=null,A5;
function u5(){if(D0===null)D0=new Intl.Segmenter(A5,{granularity:"word"});return D0}
var E5=/\p{Script=Arabic}/u,Q0=/\p{M}/u,T0=/\p{Nd}/u;
function M0(J){return E5.test(J)}
function m(J){for(let Q of J){let $=Q.codePointAt(0);if($>=19968&&$<=40959||$>=13312&&$<=19903||$>=131072&&$<=173791||$>=173824&&$<=177983||$>=177984&&$<=178207||$>=178208&&$<=183983||$>=183984&&$<=191471||$>=196608&&$<=201551||$>=63744&&$<=64255||$>=194560&&$<=195103||$>=12288&&$<=12351||$>=12352&&$<=12447||$>=12448&&$<=12543||$>=44032&&$<=55215||$>=65280&&$<=65519)return!0}return!1}
var O0=new Set(["，","．","！","：","；","？","、","。","・","）","〕","〉","》","」","』","】","〗","〙","〛","ー","々","〻","ゝ","ゞ","ヽ","ヾ"]),e=new Set(['"',"(","[","{","“","‘","«","‹","（","〔","〈","《","「","『","【","〖","〘","〚"]),K0=new Set(["'","’"]),s=new Set([".",",","!","?",":",";","،","؛","؟","।","॥","၊","။","၌","၍","၏",")","]","}","%",'"',"”","’","»","›","…"]),B5=new Set([":",".","،","؛"]),C5=new Set(["၏"]),T5=new Set(["”","’","»","›","」","』","】","》","〉","〕","）"]);
function w5(J){if(z0(J))return!0;let Q=!1;for(let $ of J){if(s.has($)){Q=!0;continue}if(Q&&Q0.test($))continue;return!1}return Q}
function y5(J){for(let Q of J)if(!O0.has(Q)&&!s.has(Q))return!1;return J.length>0}
function L5(J){if(z0(J))return!0;for(let Q of J)if(!e.has(Q)&&!K0.has(Q)&&!Q0.test(Q))return!1;return J.length>0}
function z0(J){let Q=!1;for(let $ of J){if($==="\\"||Q0.test($))continue;if(e.has($)||s.has($)||K0.has($)){Q=!0;continue}return!1}return Q}
function W5(J){let Q=Array.from(J),$=Q.length;while($>0){let X=Q[$-1];if(Q0.test(X)){$--;continue}if(e.has(X)||K0.has(X)){$--;continue}break}if($<=0||$===Q.length)return null;return{head:Q.slice(0,$).join(""),tail:Q.slice($).join("")}}
function k5(J,Q){if(J.length===0)return!1;for(let $ of J)if($!==Q)return!1;return!0}
function S5(J){if(!M0(J)||J.length===0)return!1;return B5.has(J[J.length-1])}
function I5(J){if(J.length===0)return!1;return C5.has(J[J.length-1])}
function c5(J){if(J.length<2||J[0]!==" ")return null;let Q=J.slice(1);if(/^\p{M}+$/u.test(Q))return{space:" ",marks:Q};return null}
function F0(J){for(let Q=J.length-1;Q>=0;Q--){let $=J[Q];if(T5.has($))return!0;if(!s.has($))return!1}return!1}
function h5(J,Q){if(Q.preserveOrdinarySpaces||Q.preserveHardBreaks){if(J===" ")return"preserved-space";if(J==="\t")return"tab";if(Q.preserveHardBreaks&&J===`\n`)return"hard-break"}if(J===" ")return"space";if(J===" "||J===" "||J===""||J==="\uFEFF")return"glue";if(J==="")return"zero-width-break";if(J==="")return"soft-hyphen";return"text"}
function o5(J,Q,$,X){let q=[],Z=null,Y="",D=$,N=!1,V=0;for(let U of J){let j=h5(U,X),f=j==="text"&&Q;if(Z!==null&&j===Z&&f===N){Y+=U,V+=U.length;continue}if(Z!==null)q.push({text:Y,isWordLike:N,kind:Z,start:D});Z=j,Y=U,D=$+V,N=f,V+=U.length}if(Z!==null)q.push({text:Y,isWordLike:N,kind:Z,start:D});return q}
function f0(J){return J==="space"||J==="preserved-space"||J==="zero-width-break"||J==="hard-break"}
var p5=/^[A-Za-z][A-Za-z0-9+.-]*:$/;
function x5(J,Q){let $=J.texts[Q];if($.startsWith("www."))return!0;return p5.test($)&&Q+1<J.len&&J.kinds[Q+1]==="text"&&J.texts[Q+1]==="//"}
function l5(J){return J.includes("?")&&(J.includes("://")||J.startsWith("www."))}
function m5(J){let Q=J.texts.slice(),$=J.isWordLike.slice(),X=J.kinds.slice(),q=J.starts.slice();for(let Y=0;Y<J.len;Y++){if(X[Y]!=="text"||!x5(J,Y))continue;let D=Y+1;while(D<J.len&&!f0(X[D])){Q[Y]+=Q[D],$[Y]=!0;let N=Q[D].includes("?");if(X[D]="text",Q[D]="",D++,N)break}}let Z=0;for(let Y=0;Y<Q.length;Y++){let D=Q[Y];if(D.length===0)continue;if(Z!==Y)Q[Z]=D,$[Z]=$[Y],X[Z]=X[Y],q[Z]=q[Y];Z++}return Q.length=Z,$.length=Z,X.length=Z,q.length=Z,{len:Z,texts:Q,isWordLike:$,kinds:X,starts:q}}
function g5(J){let Q=[],$=[],X=[],q=[];for(let Z=0;Z<J.len;Z++){let Y=J.texts[Z];if(Q.push(Y),$.push(J.isWordLike[Z]),X.push(J.kinds[Z]),q.push(J.starts[Z]),!l5(Y))continue;let D=Z+1;if(D>=J.len||f0(J.kinds[D]))continue;let N="",V=J.starts[D],U=D;while(U<J.len&&!f0(J.kinds[U]))N+=J.texts[U],U++;if(N.length>0)Q.push(N),$.push(!0),X.push("text"),q.push(V),Z=U-1}return{len:Q.length,texts:Q,isWordLike:$,kinds:X,starts:q}}
var r5=new Set([":","-","/","×",",",".","+","–","—"]),C0=/^[A-Za-z0-9_]+[,:;]*$/,a5=/[,:;]+$/;
function w0(J){for(let Q of J)if(T0.test(Q))return!0;return!1}
function N0(J){if(J.length===0)return!1;for(let Q of J){if(T0.test(Q)||r5.has(Q))continue;return!1}return!0}
function s5(J){let Q=[],$=[],X=[],q=[];for(let Z=0;Z<J.len;Z++){let Y=J.texts[Z],D=J.kinds[Z];if(D==="text"&&N0(Y)&&w0(Y)){let N=Y,V=Z+1;while(V<J.len&&J.kinds[V]==="text"&&N0(J.texts[V]))N+=J.texts[V],V++;Q.push(N),$.push(!0),X.push("text"),q.push(J.starts[Z]),Z=V-1;continue}Q.push(Y),$.push(J.isWordLike[Z]),X.push(D),q.push(J.starts[Z])}return{len:Q.length,texts:Q,isWordLike:$,kinds:X,starts:q}}
function d5(J){let Q=[],$=[],X=[],q=[];for(let Z=0;Z<J.len;Z++){let Y=J.texts[Z],D=J.kinds[Z],N=J.isWordLike[Z];if(D==="text"&&N&&C0.test(Y)){let V=Y,U=Z+1;while(a5.test(V)&&U<J.len&&J.kinds[U]==="text"&&J.isWordLike[U]&&C0.test(J.texts[U]))V+=J.texts[U],U++;Q.push(V),$.push(!0),X.push("text"),q.push(J.starts[Z]),Z=U-1;continue}Q.push(Y),$.push(N),X.push(D),q.push(J.starts[Z])}return{len:Q.length,texts:Q,isWordLike:$,kinds:X,starts:q}}
function i5(J){let Q=[],$=[],X=[],q=[];for(let Z=0;Z<J.len;Z++){let Y=J.texts[Z];if(J.kinds[Z]==="text"&&Y.includes("-")){let D=Y.split("-"),N=D.length>1;for(let V=0;V<D.length;V++){let U=D[V];if(!N)break;if(U.length===0||!w0(U)||!N0(U))N=!1}if(N){let V=0;for(let U=0;U<D.length;U++){let j=D[U],f=U<D.length-1?`${j}-`:j;Q.push(f),$.push(!0),X.push("text"),q.push(J.starts[Z]+V),V+=f.length}continue}}Q.push(Y),$.push(J.isWordLike[Z]),X.push(J.kinds[Z]),q.push(J.starts[Z])}return{len:Q.length,texts:Q,isWordLike:$,kinds:X,starts:q}}
function n5(J){let Q=[],$=[],X=[],q=[],Z=0;while(Z<J.len){let Y=J.texts[Z],D=J.isWordLike[Z],N=J.kinds[Z],V=J.starts[Z];if(N==="glue"){let U=Y,j=V;Z++;while(Z<J.len&&J.kinds[Z]==="glue")U+=J.texts[Z],Z++;if(Z<J.len&&J.kinds[Z]==="text")Y=U+J.texts[Z],D=J.isWordLike[Z],N="text",V=j,Z++;else{Q.push(U),$.push(!1),X.push("glue"),q.push(j);continue}}else Z++;if(N==="text")while(Z<J.len&&J.kinds[Z]==="glue"){let U="";while(Z<J.len&&J.kinds[Z]==="glue")U+=J.texts[Z],Z++;if(Z<J.len&&J.kinds[Z]==="text"){Y+=U+J.texts[Z],D=D||J.isWordLike[Z],Z++;continue}Y+=U}Q.push(Y),$.push(D),X.push(N),q.push(V)}return{len:Q.length,texts:Q,isWordLike:$,kinds:X,starts:q}}
function t5(J){let Q=J.texts.slice(),$=J.isWordLike.slice(),X=J.kinds.slice(),q=J.starts.slice();for(let Z=0;Z<Q.length-1;Z++){if(X[Z]!=="text"||X[Z+1]!=="text")continue;if(!m(Q[Z])||!m(Q[Z+1]))continue;let Y=W5(Q[Z]);if(Y===null)continue;Q[Z]=Y.head,Q[Z+1]=Y.tail+Q[Z+1],q[Z+1]=q[Z]+Y.head.length}return{len:Q.length,texts:Q,isWordLike:$,kinds:X,starts:q}}
function e5(J,Q,$){let X=u5(),q=0,Z=[],Y=[],D=[],N=[];for(let f of X.segment(J))for(let O of o5(f.segment,f.isWordLike??!1,f.index,$)){let P=O.kind==="text";if(Q.carryCJKAfterClosingQuote&&P&&q>0&&D[q-1]==="text"&&m(O.text)&&m(Z[q-1])&&F0(Z[q-1]))Z[q-1]+=O.text,Y[q-1]=Y[q-1]||O.isWordLike;else if(P&&q>0&&D[q-1]==="text"&&y5(O.text)&&m(Z[q-1]))Z[q-1]+=O.text,Y[q-1]=Y[q-1]||O.isWordLike;else if(P&&q>0&&D[q-1]==="text"&&I5(Z[q-1]))Z[q-1]+=O.text,Y[q-1]=Y[q-1]||O.isWordLike;else if(P&&q>0&&D[q-1]==="text"&&O.isWordLike&&M0(O.text)&&S5(Z[q-1]))Z[q-1]+=O.text,Y[q-1]=!0;else if(P&&!O.isWordLike&&q>0&&D[q-1]==="text"&&O.text.length===1&&O.text!=="-"&&O.text!=="—"&&k5(Z[q-1],O.text))Z[q-1]+=O.text;else if(P&&!O.isWordLike&&q>0&&D[q-1]==="text"&&(w5(O.text)||O.text==="-"&&Y[q-1]))Z[q-1]+=O.text;else Z[q]=O.text,Y[q]=O.isWordLike,D[q]=O.kind,N[q]=O.start,q++}for(let f=1;f<q;f++)if(D[f]==="text"&&!Y[f]&&z0(Z[f])&&D[f-1]==="text")Z[f-1]+=Z[f],Y[f-1]=Y[f-1]||Y[f],Z[f]="";for(let f=q-2;f>=0;f--)if(D[f]==="text"&&!Y[f]&&L5(Z[f])){let O=f+1;while(O<q&&Z[O]==="")O++;if(O<q&&D[O]==="text")Z[O]=Z[f]+Z[O],N[O]=N[f],Z[f]=""}let V=0;for(let f=0;f<q;f++){let O=Z[f];if(O.length===0)continue;if(V!==f)Z[V]=O,Y[V]=Y[f],D[V]=D[f],N[V]=N[f];V++}Z.length=V,Y.length=V,D.length=V,N.length=V;let U=n5({len:V,texts:Z,isWordLike:Y,kinds:D,starts:N}),j=t5(d5(i5(s5(g5(m5(U))))));for(let f=0;f<j.len-1;f++){let O=c5(j.texts[f]);if(O===null)continue;if(j.kinds[f]!=="space"&&j.kinds[f]!=="preserved-space"||j.kinds[f+1]!=="text"||!M0(j.texts[f+1]))continue;j.texts[f]=O.space,j.isWordLike[f]=!1,j.kinds[f]=j.kinds[f]==="preserved-space"?"preserved-space":"space",j.texts[f+1]=O.marks+j.texts[f+1],j.starts[f+1]=j.starts[f]+O.space.length}return j}
function J6(J,Q){if(J.len===0)return[];if(!Q.preserveHardBreaks)return[{startSegmentIndex:0,endSegmentIndex:J.len,consumedEndSegmentIndex:J.len}];let $=[],X=0;for(let q=0;q<J.len;q++){if(J.kinds[q]!=="hard-break")continue;$.push({startSegmentIndex:X,endSegmentIndex:q,consumedEndSegmentIndex:q+1}),X=q+1}if(X<J.len)$.push({startSegmentIndex:X,endSegmentIndex:J.len,consumedEndSegmentIndex:J.len});return $}
function y0(J,Q,$="normal"){let X=v5($),q=X.mode==="pre-wrap"?G5(J):P5(J);if(q.length===0)return{normalized:q,chunks:[],len:0,texts:[],isWordLike:[],kinds:[],starts:[]};let Z=e5(q,Q,X);return{normalized:q,chunks:J6(Z,X),...Z}}
var d=null,L0=new Map,i=null,$6=/\p{Emoji_Presentation}/u,Q6=/[\p{Emoji_Presentation}\p{Extended_Pictographic}\p{Regional_Indicator}\uFE0F\u20E3]/u,_0=null,W0=new Map;
function j0(){if(d!==null)return d;if(typeof OffscreenCanvas<"u")return d=new OffscreenCanvas(1,1).getContext("2d"),d;if(typeof document<"u")return d=document.createElement("canvas").getContext("2d"),d;throw Error("Text measurement requires OffscreenCanvas or a DOM canvas context.")}
function Z6(J){let Q=L0.get(J);if(!Q)Q=new Map,L0.set(J,Q);return Q}
function r(J,Q){let $=Q.get(J);if($===void 0)$={width:j0().measureText(J).width,containsCJK:m(J)},Q.set(J,$);return $}
function n(){if(i!==null)return i;if(typeof navigator>"u")return i={lineFitEpsilon:0.005,carryCJKAfterClosingQuote:!1,preferPrefixWidthsForBreakableRuns:!1,preferEarlySoftHyphenBreak:!1},i;let J=navigator.userAgent,$=navigator.vendor==="Apple Computer, Inc."&&J.includes("Safari/")&&!J.includes("Chrome/")&&!J.includes("Chromium/")&&!J.includes("CriOS/")&&!J.includes("FxiOS/")&&!J.includes("EdgiOS/"),X=J.includes("Chrome/")||J.includes("Chromium/")||J.includes("CriOS/")||J.includes("Edg/");return i={lineFitEpsilon:$?0.015625:0.005,carryCJKAfterClosingQuote:X,preferPrefixWidthsForBreakableRuns:$,preferEarlySoftHyphenBreak:$},i}
function q6(J){let Q=J.match(/(\d+(?:\.\d+)?)\s*px/);return Q?parseFloat(Q[1]):16}
function R0(){if(_0===null)_0=new Intl.Segmenter(void 0,{granularity:"grapheme"});return _0}
function V6(J){return $6.test(J)||J.includes("️")}
function k0(J){return Q6.test(J)}
function X6(J,Q){let $=W0.get(J);if($!==void 0)return $;let X=j0();X.font=J;let q=X.measureText("\uD83D\uDE00").width;if($=0,q>Q+0.5&&typeof document<"u"&&document.body!==null){let Z=document.createElement("span");Z.style.font=J,Z.style.display="inline-block",Z.style.visibility="hidden",Z.style.position="absolute",Z.textContent="\uD83D\uDE00",document.body.appendChild(Z);let Y=Z.getBoundingClientRect().width;if(document.body.removeChild(Z),q-Y>0.5)$=q-Y}return W0.set(J,$),$}
function Y6(J){let Q=0,$=R0();for(let X of $.segment(J))if(V6(X.segment))Q++;return Q}
function U6(J,Q){if(Q.emojiCount===void 0)Q.emojiCount=Y6(J);return Q.emojiCount}
function a(J,Q,$){if($===0)return Q.width;return Q.width-U6(J,Q)*$}
function S0(J,Q,$,X){if(Q.graphemeWidths!==void 0)return Q.graphemeWidths;let q=[],Z=R0();for(let Y of Z.segment(J)){let D=r(Y.segment,$);q.push(a(Y.segment,D,X))}return Q.graphemeWidths=q.length>1?q:null,Q.graphemeWidths}
function I0(J,Q,$,X){if(Q.graphemePrefixWidths!==void 0)return Q.graphemePrefixWidths;let q=[],Z=R0(),Y="";for(let D of Z.segment(J)){Y+=D.segment;let N=r(Y,$);q.push(a(Y,N,X))}return Q.graphemePrefixWidths=q.length>1?q:null,Q.graphemePrefixWidths}
function c0(J,Q){let $=j0();$.font=J;let X=Z6(J),q=q6(J),Z=Q?X6(J,q):0;return{cache:X,fontSize:q,emojiCorrection:Z}}
function Z0(J){return J==="space"||J==="preserved-space"||J==="tab"||J==="zero-width-break"||J==="soft-hyphen"}
function D6(J,Q){if(Q<=0)return 0;let $=J%Q;if(Math.abs($)<=1e-6)return Q;return Q-$}
function h0(J,Q,$,X){if(!X||Q===null)return J[$];return Q[$]-($>0?Q[$-1]:0)}
function M6(J,Q,$,X,q,Z){let Y=0,D=Q;while(Y<J.length){let N=Z?Q+J[Y]:D+J[Y];if((Y+1<J.length?N+q:N)>$+X)break;D=N,Y++}return{fitCount:Y,fittedWidth:D}}
function o0(J,Q){for(let $=0;$<J.chunks.length;$++){let X=J.chunks[$];if(Q<X.consumedEndSegmentIndex)return $}return-1}
function f6(J,Q){let{segmentIndex:$,graphemeIndex:X}=Q;if($>=J.widths.length)return null;if(X>0)return Q;let q=o0(J,$);if(q<0)return null;let Z=J.chunks[q];if(Z.startSegmentIndex===Z.endSegmentIndex&&$===Z.startSegmentIndex)return{segmentIndex:$,graphemeIndex:0};if($<Z.startSegmentIndex)$=Z.startSegmentIndex;while($<Z.endSegmentIndex){let Y=J.kinds[$];if(Y!=="space"&&Y!=="zero-width-break"&&Y!=="soft-hyphen")return{segmentIndex:$,graphemeIndex:0};$++}if(Z.consumedEndSegmentIndex>=J.widths.length)return null;return{segmentIndex:Z.consumedEndSegmentIndex,graphemeIndex:0}}
function p0(J,Q,$){let X=f6(J,Q);if(X===null)return null;if(J.simpleLineWalkFastPath)return N6(J,X,$);let q=o0(J,X.segmentIndex);if(q<0)return null;let Z=J.chunks[q];if(Z.startSegmentIndex===Z.endSegmentIndex)return{startSegmentIndex:Z.startSegmentIndex,startGraphemeIndex:0,endSegmentIndex:Z.consumedEndSegmentIndex,endGraphemeIndex:0,width:0};let{widths:Y,lineEndFitAdvances:D,lineEndPaintAdvances:N,kinds:V,breakableWidths:U,breakablePrefixWidths:j,discretionaryHyphenWidth:f,tabStopAdvance:O}=J,P=n(),G=P.lineFitEpsilon,A=0,T=!1,k=X.segmentIndex,p=X.graphemeIndex,E=k,B=p,w=-1,F=0,_=0,R=null;function C(){w=-1,F=0,_=0,R=null}function z(K=E,v=B,u=A){if(!T)return null;return{startSegmentIndex:k,startGraphemeIndex:p,endSegmentIndex:K,endGraphemeIndex:v,width:u}}function b(K,v){T=!0,E=K+1,B=0,A=v}function x(K,v,u){T=!0,E=K,B=v+1,A=u}function h(K,v){if(!T){b(K,v);return}A+=v,E=K+1,B=0}function S(K,v){if(!Z0(V[K]))return;let u=V[K]==="tab"?0:D[K],W=V[K]==="tab"?v:N[K];w=K+1,F=A-v+u,_=A-v+W,R=V[K]}function g(K,v){let u=U[K],W=j[K]??null;for(let I=v;I<u.length;I++){let c=h0(u,W,I,P.preferPrefixWidthsForBreakableRuns);if(!T){x(K,I,c);continue}if(A+c>$+G)return z();A+=c,E=K,B=I+1}if(T&&E===K&&B===u.length)E=K+1,B=0;return null}function L(K){if(R!=="soft-hyphen"||w<0)return null;let v=U[K]??null;if(v!==null){let u=P.preferPrefixWidthsForBreakableRuns?j[K]??v:v,W=u!==v,{fitCount:I,fittedWidth:c}=M6(u,A,$,G,f,W);if(I===v.length)return A=c,E=K+1,B=0,C(),null;if(I>0)return z(K,I,c+f)}if(F<=$+G)return z(w,0,_);return null}for(let K=X.segmentIndex;K<Z.endSegmentIndex;K++){let v=V[K],u=K===X.segmentIndex?X.graphemeIndex:0,W=v==="tab"?D6(A,O):Y[K];if(v==="soft-hyphen"&&u===0){if(T)E=K+1,B=0,w=K+1,F=A+f,_=A+f,R=v;continue}if(!T){if(u>0){let c=g(K,u);if(c!==null)return c}else if(W>$&&U[K]!==null){let c=g(K,0);if(c!==null)return c}else b(K,W);S(K,W);continue}if(A+W>$+G){let c=A+(v==="tab"?0:D[K]),z5=A+(v==="tab"?W:N[K]);if(R==="soft-hyphen"&&P.preferEarlySoftHyphenBreak&&F<=$+G)return z(w,0,_);let A0=L(K);if(A0!==null)return A0;if(Z0(v)&&c<=$+G)return h(K,W),z(K+1,0,z5);if(w>=0&&F<=$+G)return z(w,0,_);if(W>$&&U[K]!==null){let u0=z();if(u0!==null)return u0;let E0=g(K,0);if(E0!==null)return E0}return z()}h(K,W),S(K,W)}if(w===Z.consumedEndSegmentIndex&&B===0)return z(Z.consumedEndSegmentIndex,0,_);return z(Z.consumedEndSegmentIndex,0,A)}
function N6(J,Q,$){let{widths:X,kinds:q,breakableWidths:Z,breakablePrefixWidths:Y}=J,D=n(),N=D.lineFitEpsilon,V=0,U=!1,j=Q.segmentIndex,f=Q.graphemeIndex,O=j,P=f,G=-1,A=0;function T(F=O,_=P,R=V){if(!U)return null;return{startSegmentIndex:j,startGraphemeIndex:f,endSegmentIndex:F,endGraphemeIndex:_,width:R}}function k(F,_){U=!0,O=F+1,P=0,V=_}function p(F,_,R){U=!0,O=F,P=_+1,V=R}function E(F,_){if(!U){k(F,_);return}V+=_,O=F+1,P=0}function B(F,_){if(!Z0(q[F]))return;G=F+1,A=V-_}function w(F,_){let R=Z[F],C=Y[F]??null;for(let z=_;z<R.length;z++){let b=h0(R,C,z,D.preferPrefixWidthsForBreakableRuns);if(!U){p(F,z,b);continue}if(V+b>$+N)return T();V+=b,O=F,P=z+1}if(U&&O===F&&P===R.length)O=F+1,P=0;return null}for(let F=Q.segmentIndex;F<X.length;F++){let _=X[F],R=q[F],C=F===Q.segmentIndex?Q.graphemeIndex:0;if(!U){if(C>0){let b=w(F,C);if(b!==null)return b}else if(_>$&&Z[F]!==null){let b=w(F,0);if(b!==null)return b}else k(F,_);B(F,_);continue}if(V+_>$+N){if(Z0(R))return E(F,_),T(F+1,0,V-_);if(G>=0)return T(G,0,A);if(_>$&&Z[F]!==null){let b=T();if(b!==null)return b;let x=w(F,0);if(x!==null)return x}return T()}E(F,_),B(F,_)}return T()}
var H0=null,x0=new WeakMap;
function m0(){if(H0===null)H0=new Intl.Segmenter(void 0,{granularity:"grapheme"});return H0}
function O6(J){if(J)return{widths:[],lineEndFitAdvances:[],lineEndPaintAdvances:[],kinds:[],simpleLineWalkFastPath:!0,segLevels:null,breakableWidths:[],breakablePrefixWidths:[],discretionaryHyphenWidth:0,tabStopAdvance:0,chunks:[],segments:[]};return{widths:[],lineEndFitAdvances:[],lineEndPaintAdvances:[],kinds:[],simpleLineWalkFastPath:!0,segLevels:null,breakableWidths:[],breakablePrefixWidths:[],discretionaryHyphenWidth:0,tabStopAdvance:0,chunks:[]}}
function K6(J,Q,$){let X=m0(),q=n(),{cache:Z,emojiCorrection:Y}=c0(Q,k0(J.normalized)),D=a("-",r("-",Z),Y),V=a(" ",r(" ",Z),Y)*8;if(J.len===0)return O6($);let U=[],j=[],f=[],O=[],P=J.chunks.length<=1,G=$?[]:null,A=[],T=[],k=$?[]:null,p=Array.from({length:J.len}),E=Array.from({length:J.len});function B(_,R,C,z,b,x,h,S){if(b!=="text"&&b!=="space"&&b!=="zero-width-break")P=!1;if(U.push(R),j.push(C),f.push(z),O.push(b),G?.push(x),A.push(h),T.push(S),k!==null)k.push(_)}for(let _=0;_<J.len;_++){p[_]=U.length;let R=J.texts[_],C=J.isWordLike[_],z=J.kinds[_],b=J.starts[_];if(z==="soft-hyphen"){B(R,0,D,D,z,b,null,null),E[_]=U.length;continue}if(z==="hard-break"){B(R,0,0,0,z,b,null,null),E[_]=U.length;continue}if(z==="tab"){B(R,0,0,0,z,b,null,null),E[_]=U.length;continue}let x=r(R,Z);if(z==="text"&&x.containsCJK){let L="",K=0;for(let v of X.segment(R)){let u=v.segment;if(L.length===0){L=u,K=v.index;continue}if(e.has(L)||O0.has(u)||s.has(u)||q.carryCJKAfterClosingQuote&&m(u)&&F0(L)){L+=u;continue}let W=r(L,Z),I=a(L,W,Y);B(L,I,I,I,"text",b+K,null,null),L=u,K=v.index}if(L.length>0){let v=r(L,Z),u=a(L,v,Y);B(L,u,u,u,"text",b+K,null,null)}E[_]=U.length;continue}let h=a(R,x,Y),S=z==="space"||z==="preserved-space"||z==="zero-width-break"?0:h,g=z==="space"||z==="zero-width-break"?0:h;if(C&&R.length>1){let L=S0(R,x,Z,Y),K=q.preferPrefixWidthsForBreakableRuns?I0(R,x,Z,Y):null;B(R,h,S,g,z,b,L,K)}else B(R,h,S,g,z,b,null,null);E[_]=U.length}let w=z6(J.chunks,p,E),F=G===null?null:B0(J.normalized,G);if(k!==null)return{widths:U,lineEndFitAdvances:j,lineEndPaintAdvances:f,kinds:O,simpleLineWalkFastPath:P,segLevels:F,breakableWidths:A,breakablePrefixWidths:T,discretionaryHyphenWidth:D,tabStopAdvance:V,chunks:w,segments:k};return{widths:U,lineEndFitAdvances:j,lineEndPaintAdvances:f,kinds:O,simpleLineWalkFastPath:P,segLevels:F,breakableWidths:A,breakablePrefixWidths:T,discretionaryHyphenWidth:D,tabStopAdvance:V,chunks:w}}
function z6(J,Q,$){let X=[];for(let q=0;q<J.length;q++){let Z=J[q],Y=Z.startSegmentIndex<Q.length?Q[Z.startSegmentIndex]:$[$.length-1]??0,D=Z.endSegmentIndex<Q.length?Q[Z.endSegmentIndex]:$[$.length-1]??0,N=Z.consumedEndSegmentIndex<Q.length?Q[Z.consumedEndSegmentIndex]:$[$.length-1]??0;X.push({startSegmentIndex:Y,endSegmentIndex:D,consumedEndSegmentIndex:N})}return X}
function F6(J,Q,$,X){let q=y0(J,n(),X?.whiteSpace);return K6(q,Q,$)}
function g0(J,Q,$){return F6(J,Q,!0,$)}
function l0(J,Q,$){let X=$.get(J);if(X!==void 0)return X;X=[];let q=m0();for(let Z of q.segment(Q[J]))X.push(Z.segment);return $.set(J,X),X}
function _6(J){let Q=x0.get(J);if(Q!==void 0)return Q;return Q=new Map,x0.set(J,Q),Q}
function j6(J,Q,$,X){return X>0&&J[X-1]==="soft-hyphen"&&!(Q===X&&$>0)}
function R6(J,Q,$,X,q,Z,Y){let D="",N=j6(Q,X,q,Z);for(let V=X;V<Z;V++){if(Q[V]==="soft-hyphen"||Q[V]==="hard-break")continue;if(V===X&&q>0)D+=l0(V,J,$).slice(q).join("");else D+=J[V]}if(Y>0){if(N)D+="-";D+=l0(Z,J,$).slice(X===Z?q:0,Y).join("")}else if(N)D+="-";return D}
function H6(J,Q,$,X,q,Z,Y){return{text:R6(J.segments,J.kinds,Q,X,q,Z,Y),width:$,start:{segmentIndex:X,graphemeIndex:q},end:{segmentIndex:Z,graphemeIndex:Y}}}
function b6(J){return{width:J.width,start:{segmentIndex:J.startSegmentIndex,graphemeIndex:J.startGraphemeIndex},end:{segmentIndex:J.endSegmentIndex,graphemeIndex:J.endGraphemeIndex}}}
function v6(J,Q,$){let X=p0(J,Q,$);if(X===null)return null;return b6(X)}
function P6(J,Q){return H6(J,_6(J),Q.width,Q.start.segmentIndex,Q.start.graphemeIndex,Q.end.segmentIndex,Q.end.graphemeIndex)}
function b0(J,Q,$){let X=v6(J,Q,$);if(X===null)return null;return P6(J,X)}

window.g0 = g0;
window.b0 = b0;
